### PR TITLE
Fix for ByteArray transformation

### PR DESCRIPTION
**Pull request by ValentinChirikov**
Please add fix for Kotlin ByteArray transformation. Else the ts generation fails with "Empty list"

### CODE REVIEW

**Comment by dhakehurst** [comment]
Thanks

**Comment by mendess** [comment]
@dhakehurst when is a version with this fix planned to be released?

Thanks for this amazing plugin btw :)

**Comment by dhakehurst** [comment]
new release currently unplanned as I have taken to using the TS that is generated by the kotlin compiler.
you could try that, the advantage being that it works with latest kotlin version...not sure that this plugin does.

If it does not work for you, I'll try and release this again over the weekend.

**Comment by mendess** [comment]
We are trying to use the latest kotlin compiler but we are having a few issues with miscompilations. If you could release this over the weekend it would help us a lot

Thanks so much for the availability!

**Comment by dhakehurst** [comment]
which version of kotlin do you need it to work against ?

**Comment by mendess** [comment]
We are currently using ​1.4.31, so it'd be best if it worked for that version. We have uploaded this version of the plugin to our private maven repository and we found that it translates `ByteArray` to `number[]`, but the actual JS uses an `Int8Array`

**Comment by dhakehurst** [comment]
published v1.6.1, for version 1.4.32 of kotlin (as was v1.6.0)
should include your PR, not tested, let me know if issues.

**Pull request merged**
